# Generated by Django 3.0.8 on 2023-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20230823_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='paystatus',
            field=models.BooleanField(default=False),
        ),
    ]
