# Generated by Django 3.0.8 on 2023-08-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
