# Generated by Django 3.0.8 on 2023-08-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_timer_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='timer_minutes',
        ),
    ]
