# Generated by Django 3.0.8 on 2023-08-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_timer_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, verbose_name='Content')),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='essay_question',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='exam_paper',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='random_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='single_attempt',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Essay_Question',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Sitting',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
