# Generated by Django 3.0.8 on 2023-08-25 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230823_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandevents',
            old_name='title',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='posted_as',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='meet_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='stulist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='teamname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_current_semester',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_current_session',
            field=models.BooleanField(default=False),
        ),
    ]
