# Generated by Django 3.0.8 on 2023-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230825_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandevents',
            old_name='stulist',
            new_name='student_list',
        ),
        migrations.RenameField(
            model_name='newsandevents',
            old_name='teamname',
            new_name='team_name',
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='meet_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
