# Generated by Django 3.0.8 on 2023-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230825_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandevents',
            old_name='student_list',
            new_name='participants',
        ),
    ]
