# Generated by Django 3.0.8 on 2023-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
