# Generated by Django 3.0.8 on 2023-08-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
