# Generated by Django 3.0.8 on 2023-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230823_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.IntegerField(),
        ),
    ]
