# Generated by Django 3.0.8 on 2023-08-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230823_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
