# Generated by Django 3.0.8 on 2023-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230824_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.IntegerField(),
        ),
    ]
